### ISSUE TITLE
可以把添加网易云解锁么？

### ISSUE THREAD

**Issue by Benjamin23333** [gyj1109/R2S#1]
我看到你的config中把网易云解锁删掉了，可以加回来么？如果有可能的话，zerotier也可以添加吗？

**Comment by Potat0000** [comment]
a02ce05991f2b15ba3ecac58ebcb660475385546 中已添加Zerotier，初步编译后将告知版本号

**Comment by Benjamin23333** [comment]
> [a02ce05](https://github.com/gyj1109/R2S/commit/a02ce05991f2b15ba3ecac58ebcb660475385546) 中已添加Zerotier，初步编译后将告知版本号

谢谢，那网易云解锁三合一呢😅

**Comment by Potat0000** [comment]
> > [a02ce05](https://github.com/gyj1109/R2S/commit/a02ce05991f2b15ba3ecac58ebcb660475385546) 中已添加Zerotier，初步编译后将告知版本号
> 
> 谢谢，那网易云解锁三合一呢😅

9e02fa3b83179734eb708b12d58a59e0b6b2c5df ，在同一版本中编译

**Comment by Benjamin23333** [comment]
> > > [a02ce05](https://github.com/gyj1109/R2S/commit/a02ce05991f2b15ba3ecac58ebcb660475385546) 中已添加Zerotier，初步编译后将告知版本号
> > 
> > 
> > 谢谢，那网易云解锁三合一呢😅
> 
> [9e02fa3](https://github.com/gyj1109/R2S/commit/9e02fa3b83179734eb708b12d58a59e0b6b2c5df) ，在同一版本中编译

多谢

**Comment by Potat0000** [comment]
[2020-05-03T17-54](https://github.com/gyj1109/R2S/releases/tag/2020-05-03T17-54) 编译完成，包含网易云和Zerotier。后续请下载带Features后缀的版本

**Comment by Benjamin23333** [comment]
> Features

![image](https://user-images.githubusercontent.com/54323063/80916015-9c906980-8d88-11ea-9a54-1edfe808b0d6.png)
这个按钮点按后无反应
顺便说一句，“带Features后缀”是什么意思？我在release页面下载的

**Comment by Benjamin23333** [comment]
> > Features
> 
> ![image](https://user-images.githubusercontent.com/54323063/80916015-9c906980-8d88-11ea-9a54-1edfe808b0d6.png)
> 这个按钮点按后无反应
> 顺便说一句，“带Features后缀”是什么意思？我在release页面下载的

而且固件中没有v2ray

**Comment by Potat0000** [comment]
1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址

**Comment by Benjamin23333** [comment]
> 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址

v2ray可以添加，但是无法启用节点

**Comment by Benjamin23333** [comment]
> > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> 
> v2ray可以添加，但是无法启用节点

![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)

**Comment by Potat0000** [comment]
> > > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> > 
> > 
> > v2ray可以添加，但是无法启用节点
> 
> ![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)

去SSRP或Passwall更新页看看有没有下载最新的v2ray内核。另外，如果仍然不行，请另开Issue

**Comment by Benjamin23333** [comment]
> > > > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > > > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > > > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> > > 
> > > 
> > > v2ray可以添加，但是无法启用节点
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)
> 
> 去SSRP或Passwall更新页看看有没有下载最新的v2ray内核。另外，如果仍然不行，请另开Issue

我可以直接在这里请求下次编译的时候带上v2ray么

**Comment by Potat0000** [comment]
> > > > > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > > > > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > > > > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> > > > 
> > > > 
> > > > v2ray可以添加，但是无法启用节点
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)
> > 
> > 
> > 去SSRP或Passwall更新页看看有没有下载最新的v2ray内核。另外，如果仍然不行，请另开Issue
> 
> 我可以直接在这里请求下次编译的时候带上v2ray么

问题就是，我已经把所有有关v2ray的都带上了。v2ray内核只能自己去ssrp和passwall页面下载更新。如果还不行，应该是上游出了问题

**Comment by Benjamin23333** [comment]
> > > > > > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > > > > > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > > > > > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> > > > > 
> > > > > 
> > > > > v2ray可以添加，但是无法启用节点
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)
> > > 
> > > 
> > > 去SSRP或Passwall更新页看看有没有下载最新的v2ray内核。另外，如果仍然不行，请另开Issue
> > 
> > 
> > 我可以直接在这里请求下次编译的时候带上v2ray么
> 
> 问题就是，我已经把所有有关v2ray的都带上了。v2ray内核只能自己去ssrp和passwall页面下载更新。如果还不行，应该是上游出了问题

这样啊，我试着在passwall里更新v2ray，一直显示下载中，我scp进路由器看，发现v2ray的文件已经在tmp里下好了，可是卡住了，不解压也不安装

**Comment by Benjamin23333** [comment]
> > > > > > > 1、TG群内反馈，SSRP最新版似乎有Bug，这个按钮无效，暂时需要手工输入。这个需要等待上游更新。
> > > > > > > 2、请查看最新的README，今后的固件将带有SelfUse和WithFeatures标签。Zerotier只包含在WithFeatures版本中，因为我自己用不到。
> > > > > > > 3、我自己不用v2ray，所以无法测试，但固件应该包含v2ray。Passwall和SSRP中试试看能不能添加v2ray地址
> > > > > > 
> > > > > > 
> > > > > > v2ray可以添加，但是无法启用节点
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/54323063/80916313-7ec40400-8d8a-11ea-952d-9255b1ef39f3.png)
> > > > 
> > > > 
> > > > 去SSRP或Passwall更新页看看有没有下载最新的v2ray内核。另外，如果仍然不行，请另开Issue
> > > 
> > > 
> > > 我可以直接在这里请求下次编译的时候带上v2ray么
> > 
> > 
> > 问题就是，我已经把所有有关v2ray的都带上了。v2ray内核只能自己去ssrp和passwall页面下载更新。如果还不行，应该是上游出了问题
> 
> 这样啊，我试着在passwall里更新v2ray，一直显示下载中，我scp进路由器看，发现v2ray的文件已经在tmp里下好了，可是卡住了，不解压也不安装

我这次吧v2ray的主程序直接拖进去了，不现实找不到主程序了，但是v2ray节点仍然无法运行的，我这就去开新issue
