### ISSUE TITLE
ssr+无法运行，passwall无法启用v2ray节点

### ISSUE THREAD

**Issue by Benjamin23333** [gyj1109/R2S#2]
ssr+一直显示“正在收集数据”，无法运行，passwall无法启用v2ray节点，显示找不到主程序手动拖入主程序，主程序成功找到，但是仍然无法启用节点，tcp显示未运行

**Comment by Potat0000** [comment]
ssr+请等待上游更新。Passwall我自己试了一下，在已有梯子的情况下可以正常更新v2ray内核。由于没有v2ray服务器，无法测试能否启用节点。建议先启用其他备用梯子后再更新，因为内核更新地址是Github的，部分地区链接慢或被墙

**Comment by Benjamin23333** [comment]
> ssr+请等待上游更新。Passwall我自己试了一下，在已有梯子的情况下可以正常更新v2ray内核。由于没有v2ray服务器，无法测试能否启用节点。建议先启用其他备用梯子后再更新，因为内核更新地址是Github的，部分地区链接慢或被墙

ssr+似乎是固件的问题，源码bug是无法导入节点配置，而固件里的bug是一直显示“正在收集数据”。
passwall的v2ray内核我手动拖入了，日志没有显示报错，但是v2ray节点仍然无法运行。

**Comment by Potat0000** [comment]
在`2020-05-04T14-38`版中我修改了上游源，可能可以修复ssr+和passwall的问题。如果能编译通过的话你可以试试

**Comment by Potat0000** [comment]
如果有别的问题的话等下周周末我来修，高三狗五一都要少一天……

**Comment by Benjamin23333** [comment]
> 如果有别的问题的话等下周周末我来修，高三狗五一都要少一天……

多谢

**Comment by Potat0000** [comment]
已迁移至 [gyj1109/R2S-OpenWrt](https://github.com/gyj1109/R2S-OpenWrt)，但已不包含SSRP和Passwall，只含有OpenClash
